name: Run Tests on Schedule


on:
  schedule:
    - cron: '0 0 */1 * *'  
  workflow_dispatch:  

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout the code from the repository
        uses: actions/checkout@v2  

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run tests
        run: |
          python -m unittest discover 
        working-directory: ./tests  
